name: Deploy Jekyll Site with Tailwind CSS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: false

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
    
      - name: Disable frozen mode
        run: bundle config set frozen false

      - name: Install dependencies
        run: |
          bundle install
          bundle exec npm install --save-dev

      - name: Build site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
